### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Sboursen** [UpliftLab/al-mentoria-backend#9]
# Hello :wave: 

:point_right: [Project link](https://github.com/orgs/UpliftLab/projects/3)

We are a group of **four** people

![image](https://user-images.githubusercontent.com/51741471/177760507-48738c6d-9d42-4d21-a383-9b122370b95e.png)

Cheers :grin:

**Comment by MuriloRoque** [comment]
Hi @Sboursen, @mirouhml,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by mirouhml** [comment]
Thanks for the review @MuriloRoque.
